### Create a report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Mustang",
    "year": 2015,
    "mileage": 2100,
    "longitude": 1.9403,
    "latitude": 29.8739,
    "price": 2300
}


### Update report's staus

PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}