### Create a report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 2004,
    "mileage": 2100,
    "longitude": 1.9403,
    "latitude": 29.8739,
    "price": 100
}


### Update report's staus

PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}


### Get estimated price for the cars

GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2013&mileage=1000&longitude=0&latitude=27